user:
  mail:
  latitude:
  longitude:
  # Hours different to UTC time
  time_difference:
technical:
  # Mains Voltage in Volt
  mains_voltage:
  # Buffer in Watt
  buffer:
  min_charging_amp:
  max_charging_amp:
  powerwall_limit:
  # Time between measurements in seconds. Tested and recommended 300 = 5 min
  sleep_time:
