user:
  mail:
  latitude:
  longitude:
technical:
  # Mains Voltage in Volt
  mains_voltage:
  # Buffer in Watt
  buffer:
  min_charging_amp:
  max_charging_amp:
  # Time between measurements in seconds 900 = 15 min
  sleep_time:
